In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re

file_jan = '/mnt/data06/andyxia/data/death_data/neg_jan/Jan_death_data.json'
file_feb = '/mnt/data06/andyxia/data/death_data/neg_feb/Feb_death_data.json'
file_mar = '/mnt/data06/andyxia/data/death_data/neg_mar/Mar_death_data.json'
file_apr = '/mnt/data06/andyxia/data/death_data/neg_apr/Apr_death_data.json'
file_may = '/mnt/data06/andyxia/data/death_data/neg_may/May_death_data.json'
file_jun = '/mnt/data06/andyxia/data/death_data/neg_jun/Jun_death_data.json'
file_jul = '/mnt/data06/andyxia/data/death_data/neg_jul/Jul_death_data.json'
file_aug = '/mnt/data06/andyxia/data/death_data/neg_aug/Aug_death_data.json'
file_sep = '/mnt/data06/andyxia/data/death_data/neg_sep/Sep_death_data.json'
file_oct = '/mnt/data06/andyxia/data/death_data/neg_oct/Oct_death_data.json'
file_nov = '/mnt/data06/andyxia/data/death_data/neg_nov/Nov_death_data.json'
file_dec = '/mnt/data06/andyxia/data/death_data/neg_dec/Dec_death_data.json'
df1 = pd.read_json(file_jan)
df2 = pd.read_json(file_feb)
df3 = pd.read_json(file_mar)
df4 = pd.read_json(file_apr)
df5 = pd.read_json(file_may)
df6 = pd.read_json(file_jun)
df7 = pd.read_json(file_jul)
df8 = pd.read_json(file_aug)
df9 = pd.read_json(file_sep)
df10 = pd.read_json(file_oct)
df11 = pd.read_json(file_nov)
df12 = pd.read_json(file_dec)
df=pd.concat([df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12], ignore_index=True)

### Load your data with false labels
df = pd.read_json('Path to your data')
df

/tmp/ipykernel_4122797/3862758429.py:21: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  df3 = pd.read_json(file_mar)
/tmp/ipykernel_4122797/3862758429.py:21: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  df3 = pd.read_json(file_mar)
/tmp/ipykernel_4122797/3862758429.py:21: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  df3 = pd.read_json(file_mar)
/tmp/ipykernel_4122797/3862758429.py:22: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  df4 = pd.read_json(file_apr)
/tmp/ipykernel_4122797/3862758429.py:22: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  df4 = pd.read_json(file_apr)
/tmp/ipykernel_4122797/3862758429.py:22: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  df4 = pd.read_json(file_apr)
/tmp/ipykernel_4122797/3862758429.py:23: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  df5 = pd.read_json(file_may)
/tmp/ipykernel_4122797/3862758429.py:23: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  df5 = pd.read_json(file_may)
/tmp/ipykernel_4122797/3862758429.py:23: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  df5 = pd.read_json(file_may)
/tmp/ipykernel_4122797/3862758429.py:24: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  df6 = pd.read_json(file_jun)
/tmp/ipykernel_4122797/3862758429.py:24: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  df6 = pd.read_json(file_jun)
/tmp/ipykernel_4122797/3862758429.py:24: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  df6 = pd.read_json(file_jun)
/tmp/ipykernel_4122797/3862758429.py:25: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  df7 = pd.read_json(file_jul)
/tmp/ipykernel_4122797/3862758429.py:25: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  df7 = pd.read_json(file_jul)
/tmp/ipykernel_4122797/3862758429.py:25: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  df7 = pd.read_json(file_jul)
/tmp/ipykernel_4122797/3862758429.py:26: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  df8 = pd.read_json(file_aug)
/tmp/ipykernel_4122797/3862758429.py:26: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  df8 = pd.read_json(file_aug)
/tmp/ipykernel_4122797/3862758429.py:26: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  df8 = pd.read_json(file_aug)
/tmp/ipykernel_4122797/3862758429.py:27: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  df9 = pd.read_json(file_sep)
/tmp/ipykernel_4122797/3862758429.py:27: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  df9 = pd.read_json(file_sep)
/tmp/ipykernel_4122797/3862758429.py:27: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  df9 = pd.read_json(file_sep)
/tmp/ipykernel_4122797/3862758429.py:28: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  df10 = pd.read_json(file_oct)
/tmp/ipykernel_4122797/3862758429.py:28: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  df10 = pd.read_json(file_oct)
/tmp/ipykernel_4122797/3862758429.py:28: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  df10 = pd.read_json(file_oct)
/tmp/ipykernel_4122797/3862758429.py:30: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  df12 = pd.read_json(file_dec)
/tmp/ipykernel_4122797/3862758429.py:30: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  df12 = pd.read_json(file_dec)
/tmp/ipykernel_4122797/3862758429.py:30: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  df12 = pd.read_json(file_dec)

,error,original_demo,0,1,2,3,4,5,6,7,...,53,54,55,56,57,58,59,60,61,62
0,None,Jan/1win-vs-endpoint-m2-dust2_2354113.dem,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,"[{'playerName': '1WIN.travis19K', 'side': 't',...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,"[{'playerName': '1WIN.glowiing', 'side': 't', ...",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,"[{'playerName': '1WIN.deko', 'side': 't', 'tic...",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,"[{'playerName': '1WIN.2flamie', 'side': 't', '...",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33041,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33042,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33043,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33044,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33045,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
import math
def distance(p1, p2):
    return math.sqrt((p1['lastKnownPosition'][0] - p2['lastKnownPosition'][0]) ** 2 +
                     (p1['lastKnownPosition'][1] - p2['lastKnownPosition'][1]) ** 2 +
                     (p1['lastKnownPosition'][2] - p2['lastKnownPosition'][2]) ** 2)

def check_direction(velocity, position1, position2):

    direction_vector = np.array(position2) - np.array(position1)
    velocity_vector = np.array([velocity['velocityX'], velocity['velocityY'], velocity['velocityZ']])
    dot_product = np.dot(direction_vector, velocity_vector)
    return dot_product > 0
    
def get_additional_features(players):

    specific_players = [player for player in players if "will_die" in player]
    results = []
    # print(len(specific_players))
    # if len(specific_players)==1:
    #     for player in players:
            # print(player)
    for specific_player in specific_players:
        teammate_distances = []
        enemy_distances = []

        # Calculate distances from the specific player to others
        teammate_alive=1
        enemy_alive=0
        total_teammate_health=specific_player["hp"]
        total_enemy_health=0
        teamEqVal=specific_player["equipment_value"]
        enemy_teamEqVal=0
        hp_diff_with_enemy=0
        closest_dist=1000000
        closest_player=None
        num_enemies_ahead=0
        for player in players:
            if player != specific_player:
                # print(player)
                # print(specific_player['side'])
                if player['side'] == specific_player['side']:
                    teammate_distances.append(distance(specific_player, player))
                    if player['is_alive']:
                        teammate_alive+=1
                    total_teammate_health+=player['hp']
                    teamEqVal+=player["equipment_value"]
                else:
                    enemy_distance = distance(specific_player, player)
                    enemy_distances.append(enemy_distance)
                    if enemy_distance < closest_dist:
                        closest_player = player
                        closest_dist = enemy_distance
                    if player['is_alive']:
                        enemy_alive+=1
                    total_enemy_health+=player['hp']
                    enemy_teamEqVal+=player["equipment_value"]
                    if check_direction({'velocityX': specific_player['velocityX'], 'velocityY': specific_player['velocityY'], 'velocityZ': specific_player['velocityZ']},
                                          specific_player['lastKnownPosition'],
                                          player['lastKnownPosition']):
                        num_enemies_ahead+=1

        if enemy_alive==0:
            enemy_alive=1
        avg_teammate_distance = sum(teammate_distances) / len(teammate_distances) if teammate_distances else 0
        avg_enemy_distance = sum(enemy_distances) / len(enemy_distances) if enemy_distances else 0
        avg_teammate_health = total_teammate_health / teammate_alive
        avg_enemy_health = total_enemy_health / enemy_alive
        econ_disparity = teamEqVal - enemy_teamEqVal
        hp_diff_with_enemy = specific_player['hp'] - closest_player['hp']
        specific_player["average_teammate_distance"] = avg_teammate_distance
        specific_player["average_enemy_distance"] = avg_enemy_distance
        specific_player["avg_teammate_health"] =  avg_teammate_health
        specific_player["avg_enemy_health"] = avg_enemy_health
        specific_player["econ_disparity"] = econ_disparity
        specific_player["hp_diff_with_enemy"] = hp_diff_with_enemy
        specific_player["num_enemies_ahead"] = num_enemies_ahead
        results.append(specific_player)
    return results


def read(file):
    stats=[]
    counter=0
    holder=[]
    data_array=np.array(file)
    # printer=0
    # print(data_array)
    for entry in data_array:
        # print(entry[0])
        if entry[0]!='None':
            for index, value in enumerate(entry):
                if isinstance(value, list):
                    for player in value:
                        holder.append(player)

                        if len(holder)==10:
                            result=get_additional_features(holder)
                            for x in range(len(result)):
                                stats.append(result[x])
                            # stats.append(result[1])
                            holder=[]
                        
    return stats

stats = read(df)
# stats.pop('lastKnownPosition')
stats = pd.DataFrame(stats)
stats = stats.drop(columns=['playerName', 'is_alive', 'lastKnownPosition', 'velocityX', 'velocityY', 'velocityZ', 'viewX', 'viewY', 'side', 'tick', 'survives_round'])
print(stats.columns)
dummy_col = ['active_weapon_category', 'primary_weapon', 'secondary_weapon', 'is_blinded', 'is_ducking', 'is_scoped', 'has_helmet', 'has_defuser', 'callout']
stats = pd.get_dummies(stats, columns = dummy_col)
stats

Index(['hp', 'armor', 'equipment_value', 'cash', 'cash_spend_this_round',
       'round_damage', 'primary_weapon', 'secondary_weapon',
       'active_weapon_category', 'grenades_left', 'flashes_left',
       'smokes_left', 'molotovs_left', 'is_blinded', 'is_ducking', 'is_scoped',
       'has_helmet', 'has_defuser', 'total_kills', 'round_kills',
       'total_deaths', 'callout', 'average_damage_per_round', 'will_die',
       'average_teammate_distance', 'average_enemy_distance',
       'avg_teammate_health', 'avg_enemy_health', 'econ_disparity',
       'hp_diff_with_enemy', 'num_enemies_ahead'],
      dtype='object')

,hp,armor,equipment_value,cash,cash_spend_this_round,round_damage,grenades_left,flashes_left,smokes_left,molotovs_left,...,callout_Ramp,callout_Short,callout_ShortStairs,callout_Side,callout_TRamp,callout_TSpawn,callout_TopofMid,callout_TunnelStairs,callout_UnderA,callout_UpperTunnel
0,100,100,850,150,650,0,0,0,0,0,...,False,False,False,False,False,False,False,False,False,False
1,100,0,1000,0,800,0,0,2,0,0,...,False,False,False,False,False,False,False,False,False,False
2,100,100,850,150,650,0,0,0,0,0,...,False,False,False,False,False,False,False,False,False,False
3,100,100,850,150,650,0,0,0,0,0,...,False,False,False,False,False,False,False,False,False,False
4,40,68,850,450,650,60,0,0,0,0,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
985192,100,100,5100,1700,2200,0,1,1,1,1,...,False,False,False,False,False,False,False,False,False,False
985193,100,100,5550,1150,2450,0,1,1,1,0,...,False,False,False,False,False,False,False,False,False,False
985194,100,100,5000,900,7500,0,0,2,1,1,...,False,False,False,False,False,False,False,False,False,False
985195,100,96,4800,0,3800,0,0,0,1,0,...,False,False,False,False,False,False,False,False,False,False
985196,100,100,7150,1700,7150,0,0,2,1,1,...,False,False,False,False,False,False,False,False,False,False

In [13]:
dead=0
not_dead=0
for index, x in stats.iterrows():
    if x['will_die']==0:
        not_dead+=1
    elif x['will_die']==1:
        dead+=1

print(f"dead:{dead}   not_dead:{not_dead}")

dead:0   not_dead:985197

In [14]:
# file_jan = '/mnt/data06/andyxia/data/death_data/test_jan/Jan_death_data.json'
# file_feb = '/mnt/data06/andyxia/data/death_data/test_feb/Feb_death_data.json'
# file_mar = '/mnt/data06/andyxia/data/death_data/test_mar/Mar_death_data.json'
# file_apr = '/mnt/data06/andyxia/data/death_data/test_apr/Apr_death_data.json'
# file_may = '/mnt/data06/andyxia/data/death_data/test_may/May_death_data.json'
# file_jun = '/mnt/data06/andyxia/data/death_data/test_jun/Jun_death_data.json'
# file_jul = '/mnt/data06/andyxia/data/death_data/test_jul/Jul_death_data.json'
# file_aug = '/mnt/data06/andyxia/data/death_data/test_aug/Aug_death_data.json'
# file_sep = '/mnt/data06/andyxia/data/death_data/test_sep/Sep_death_data.json'
# file_oct = '/mnt/data06/andyxia/data/death_data/test_oct/Oct_death_data.json'
# file_nov = '/mnt/data06/andyxia/data/death_data/test_nov/Nov_death_data.json'
# file_dec = '/mnt/data06/andyxia/data/death_data/test_dec/Dec_death_data.json'
# df1 = pd.read_json(file_jan)
# df2 = pd.read_json(file_feb)
# df3 = pd.read_json(file_mar)
# df4 = pd.read_json(file_apr)
# df5 = pd.read_json(file_may)
# df6 = pd.read_json(file_jun)
# df7 = pd.read_json(file_jul)
# df8 = pd.read_json(file_aug)
# df9 = pd.read_json(file_sep)
# df10 = pd.read_json(file_oct)
# df11 = pd.read_json(file_nov)
# df12 = pd.read_json(file_dec)
# df_pos=pd.concat([df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12], ignore_index=True)

### Load your data with true labels
df_pos = pd.read_json('Path to your data with dead players')

stats_pos = read(df_pos)
# stats.pop('lastKnownPosition')
stats_pos = pd.DataFrame(stats_pos)
stats_pos = stats_pos.drop(columns=['playerName', 'is_alive', 'lastKnownPosition', 'velocityX', 'velocityY', 'velocityZ', 'viewX', 'viewY', 'side', 'tick', 'survives_round'])
print(stats_pos.columns)
dummy_col = ['active_weapon_category', 'primary_weapon', 'secondary_weapon', 'is_blinded', 'is_ducking', 'is_scoped', 'has_helmet', 'has_defuser', 'callout']
stats_pos = pd.get_dummies(stats_pos, columns = dummy_col)
stats_pos

/tmp/ipykernel_4122797/3046617432.py:18: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  df3 = pd.read_json(file_mar)
/tmp/ipykernel_4122797/3046617432.py:18: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  df3 = pd.read_json(file_mar)
/tmp/ipykernel_4122797/3046617432.py:18: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  df3 = pd.read_json(file_mar)
/tmp/ipykernel_4122797/3046617432.py:19: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  df4 = pd.read_json(file_apr)
/tmp/ipykernel_4122797/3046617432.py:19: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  df4 = pd.read_json(file_apr)
/tmp/ipykernel_4122797/3046617432.py:19: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  df4 = pd.read_json(file_apr)
/tmp/ipykernel_4122797/3046617432.py:20: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  df5 = pd.read_json(file_may)
/tmp/ipykernel_4122797/3046617432.py:20: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  df5 = pd.read_json(file_may)
/tmp/ipykernel_4122797/3046617432.py:20: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  df5 = pd.read_json(file_may)
/tmp/ipykernel_4122797/3046617432.py:21: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  df6 = pd.read_json(file_jun)
/tmp/ipykernel_4122797/3046617432.py:21: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  df6 = pd.read_json(file_jun)
/tmp/ipykernel_4122797/3046617432.py:21: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  df6 = pd.read_json(file_jun)
/tmp/ipykernel_4122797/3046617432.py:22: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  df7 = pd.read_json(file_jul)
/tmp/ipykernel_4122797/3046617432.py:22: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  df7 = pd.read_json(file_jul)
/tmp/ipykernel_4122797/3046617432.py:22: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  df7 = pd.read_json(file_jul)
/tmp/ipykernel_4122797/3046617432.py:23: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  df8 = pd.read_json(file_aug)
/tmp/ipykernel_4122797/3046617432.py:23: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  df8 = pd.read_json(file_aug)
/tmp/ipykernel_4122797/3046617432.py:23: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  df8 = pd.read_json(file_aug)
/tmp/ipykernel_4122797/3046617432.py:24: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  df9 = pd.read_json(file_sep)
/tmp/ipykernel_4122797/3046617432.py:24: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  df9 = pd.read_json(file_sep)
/tmp/ipykernel_4122797/3046617432.py:24: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  df9 = pd.read_json(file_sep)
/tmp/ipykernel_4122797/3046617432.py:25: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  df10 = pd.read_json(file_oct)
/tmp/ipykernel_4122797/3046617432.py:25: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  df10 = pd.read_json(file_oct)
/tmp/ipykernel_4122797/3046617432.py:25: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  df10 = pd.read_json(file_oct)
/tmp/ipykernel_4122797/3046617432.py:27: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  df12 = pd.read_json(file_dec)
/tmp/ipykernel_4122797/3046617432.py:27: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  df12 = pd.read_json(file_dec)
/tmp/ipykernel_4122797/3046617432.py:27: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  df12 = pd.read_json(file_dec)

Index(['hp', 'armor', 'equipment_value', 'cash', 'cash_spend_this_round',
       'round_damage', 'primary_weapon', 'secondary_weapon',
       'active_weapon_category', 'grenades_left', 'flashes_left',
       'smokes_left', 'molotovs_left', 'is_blinded', 'is_ducking', 'is_scoped',
       'has_helmet', 'has_defuser', 'total_kills', 'round_kills',
       'total_deaths', 'callout', 'average_damage_per_round', 'will_die',
       'average_teammate_distance', 'average_enemy_distance',
       'avg_teammate_health', 'avg_enemy_health', 'econ_disparity',
       'hp_diff_with_enemy', 'num_enemies_ahead'],
      dtype='object')

,hp,armor,equipment_value,cash,cash_spend_this_round,round_damage,grenades_left,flashes_left,smokes_left,molotovs_left,...,callout_Ramp,callout_Short,callout_ShortStairs,callout_Side,callout_TRamp,callout_TSpawn,callout_TopofMid,callout_TunnelStairs,callout_UnderA,callout_UpperTunnel
0,100,100,850,150,650,0,0,0,0,0,...,False,False,False,False,False,False,False,False,False,False
1,6,100,850,150,650,0,0,0,0,0,...,False,False,False,False,False,False,False,False,False,False
2,100,100,850,150,650,0,0,0,0,0,...,False,False,False,False,False,False,False,False,False,False
3,100,100,850,150,650,0,0,0,0,0,...,False,False,False,False,False,False,False,False,False,False
4,100,0,800,0,800,0,0,1,0,0,...,False,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375530,92,97,7150,50,4900,7,0,0,0,0,...,False,False,False,False,False,False,False,False,False,False
375531,93,97,5300,1250,5700,8,0,1,0,0,...,False,False,False,False,False,False,False,False,False,False
375532,92,97,7150,150,4900,107,0,0,0,0,...,False,False,False,False,False,False,False,False,False,False
375533,66,90,5900,5900,4300,153,0,0,0,0,...,False,False,False,False,False,False,False,False,False,False
375534,68,100,3900,300,4800,43,0,0,0,0,...,False,False,False,False,False,False,False,False,False,False

In [26]:
import json
from tqdm import tqdm
from sklearn.metrics.pairwise import pairwise_distances

positive_labels = stats_pos[stats_pos['will_die']==1]

cols=[]
for col in positive_labels.columns:
    if col not in cols:
        cols.append(col)

for col in stats.columns:
    if col not in cols:
        cols.append(col)

for col in cols:
    if col not in positive_labels.columns:
        positive_labels[col] = 0
    if col not in stats.columns:
        stats[col] = 0

positive_labels_np = positive_labels.to_numpy()
stats_np = stats.to_numpy()

batch_size = 1000
euc_dist = []
for i in tqdm(range(0, len(stats_np), batch_size), desc = 'batch_processing'):
    stats_batch = stats_np[i:i+batch_size]
    distance_matrix = pairwise_distances(stats_batch, positive_labels_np, metric='euclidean')
    euc_dist.extend(distance_matrix.mean(axis=1))
stats['euc_dist']=euc_dist
sorted_stats = stats.sort_values(by = 'euc_dist', ascending = False)
loc=list(range(len(positive_labels)*1))
false_labels = sorted_stats.iloc[loc]

false_labels = false_labels.drop('euc_dist', axis=1)
fullset = pd.concat([positive_labels,false_labels])

batch_processing: 100%|████████████████████████████████████████████████████████████████████████████████████████| 986/986 [1:02:07<00:00,  3.78s/it]

In [27]:
fullset.replace({'False': 0, 'True': 1}, inplace=True)

In [32]:
X = fullset.drop(columns=['will_die'])
y = fullset['will_die']

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
from sklearn.preprocessing import StandardScaler

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("Classification Report:\n", report)

Accuracy: 0.7639492462041955
Classification Report:
               precision    recall  f1-score   support

           0       0.75      0.79      0.77     37251
           1       0.78      0.74      0.76     37305

    accuracy                           0.76     74556
   macro avg       0.76      0.76      0.76     74556
weighted avg       0.76      0.76      0.76     74556

In [30]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix
model = DecisionTreeClassifier(max_depth=3, random_state=42)

model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print("Accuracy:",accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.9127501475401041
              precision    recall  f1-score   support

           0       0.86      0.99      0.92     37251
           1       0.99      0.83      0.91     37305

    accuracy                           0.91     74556
   macro avg       0.92      0.91      0.91     74556
weighted avg       0.92      0.91      0.91     74556

In [31]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.7377944095713289
Classification Report:
               precision    recall  f1-score   support

           0       0.72      0.77      0.75     37251
           1       0.75      0.71      0.73     37305

    accuracy                           0.74     74556
   macro avg       0.74      0.74      0.74     74556
weighted avg       0.74      0.74      0.74     74556